sudo: true
dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - git
    - curl
    - libelf-dev
    - flex
    - bison
    - autoconf
    - python3-pip

before_install:
  - sudo pip3 install --upgrade pip setuptools
  - sudo pip3 install --ignore-installed six

install:
  - .travis/install-${JOB}.sh

script:
  - .travis/run-${JOB}.sh

jobs:
  fail_fast: true

  include:
    - stage: verilator
      env: JOB=verilator
    - stage: or1k-tests
      env: JOB=or1k-tests PIPELINE=CAPPUCCINO
    - stage: or1k-tests
      env: JOB=or1k-tests PIPELINE=ESPRESSO
