language: c
cache: ccache
sudo: true
dist: trusty

services:
  - docker 

addons:
  apt:
    packages:
    - build-essential
    - git
    - curl
    - libelf-dev
    - flex
    - bison
    - autoconf
    - python3-pip

before_install:
  -  docker pull librecores/librecores-ci

install:
  -  docker run --rm librecores/librecores-ci
  - .travis/install-or1k-tests.sh

script:
  - export PIPELINE=${P}
  - export EXPECTED_FAILURES=${EF}
  - export EXTRA_CORE_ARGS=${EXTRA}
  - .travis/run-${JOB}.sh

matrix:
  fast_finish: true

jobs:
  allow_failures:
    - env: JOB=or1k-tests SIM=icarus P=ESPRESSO
  include:
    - stage: verilator
      env: JOB=verilator
    - stage: testing
      env: JOB=or1k-tests SIM=icarus P=CAPPUCCINO EF="or1k-cy"
    - stage: testing
      env: JOB=or1k-tests SIM=icarus P=CAPPUCCINO EF="or1k-cy" EXTRA="--feature_dmmu NONE"
    - stage: testing
      env: JOB=or1k-tests SIM=icarus P=CAPPUCCINO EF="or1k-cy or1k-dsxinsn" EXTRA="--feature_immu NONE"
    - stage: testing
      env: JOB=or1k-tests SIM=icarus P=CAPPUCCINO EF="or1k-cy" EXTRA="--feature_datacache NONE"
    - stage: testing
      env: JOB=or1k-tests SIM=icarus P=CAPPUCCINO EF="or1k-cy" EXTRA="--feature_instructioncache NONE"
    - stage: testing
      env: JOB=or1k-tests SIM=icarus P=CAPPUCCINO EF="or1k-cy" EXTRA="--feature_debugunit NONE"
    - stage: testing
      env: JOB=or1k-tests SIM=icarus P=CAPPUCCINO EF="or1k-cy or1k-cmov" EXTRA="--feature_cmov NONE"
    - stage: testing
      env: JOB=or1k-tests SIM=icarus P=CAPPUCCINO EF="or1k-cy or1k-ext" EXTRA="--feature_ext NONE"
    - stage: testing
      env: JOB=or1k-tests SIM=icarus P=ESPRESSO

