sudo: true
dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - git
    - curl
    - libelf-dev
    - flex
    - bison
    - autoconf
    - python3-pip

before_install:
  - sudo pip3 install --upgrade pip setuptools
  - sudo pip3 install --ignore-installed six
  - sudo pip3 install fusesoc

install:
  - .travis/install-verilator.sh
  - .travis/install-fusesoc.sh

script:
  - verilator --lint-only rtl/verilog/*.v +incdir+rtl/verilog
  - .travis/run-or1k-tests.sh
