language: c
cache: ccache
sudo: true
dist: trusty

services:
  - docker 

before_install:
  -  docker pull librecores/librecores-ci
  -  docker images

install:
  -  docker run --rm -v $(pwd):/src librecores/librecores-ci /src/.travis/test.sh
  